# Generated by Django 3.2.7 on 2022-08-18 11:33

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220818_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cost', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(default='default.png')),
                ('wattage_capacity', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
            options={
                'verbose_name': 'Inverter',
                'verbose_name_plural': 'Inverters',
            },
        ),
        migrations.AddIndex(
            model_name='inverter',
            index=models.Index(fields=['wattage_capacity', 'id'], name='product_inv_wattage_e8e988_idx'),
        ),
    ]
