# Generated by Django 3.2.7 on 2022-08-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220818_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
    ]
