# Generated by Django 3.2.7 on 2022-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productvariant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
