# Generated by Django 3.2.7 on 2022-08-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220821_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
