# Generated by Django 3.2.7 on 2022-08-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productvariant_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shipping_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
