# Generated by Django 3.2.7 on 2022-08-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0012_alter_quote_inverter'),
        ('product', '0015_auto_20220823_0706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inverter',
        ),
    ]
