# Generated by Django 3.2.7 on 2022-08-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20220824_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'In stock'), ('Out of stock', 'Out of stock')], max_length=15),
        ),
    ]
