# Generated by Django 3.2.7 on 2022-08-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Solar Panel', 'verbose_name_plural': 'Solar Panels'},
        ),
    ]
