# Generated by Django 3.2.7 on 2022-08-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, help_text='For cables', max_length=10, null=True),
        ),
    ]
