# Generated by Django 3.2.7 on 2022-08-31 07:30

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productvariant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=djrichtextfield.models.RichTextField(default=True),
            preserve_default=False,
        ),
    ]
