# Generated by Django 3.2.7 on 2022-09-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20220902_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
