# Generated by Django 3.2.7 on 2022-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_primary_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
