# Generated by Django 3.2.7 on 2022-09-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_productvariant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='wattage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
