# Generated by Django 3.2.7 on 2022-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_productvariant_wattage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height',
            field=models.CharField(blank=True, help_text='For panels', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width',
            field=models.CharField(blank=True, help_text='For panels', max_length=50, null=True),
        ),
    ]
