# Generated by Django 3.2.7 on 2022-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20220913_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='height',
            field=models.CharField(blank=True, help_text='For panels. (metres)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width',
            field=models.CharField(blank=True, help_text='For panels. (metres)', max_length=50, null=True),
        ),
    ]
