# Generated by Django 3.2.7 on 2022-09-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productvariant_suitable_roof_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='tax',
        ),
    ]
