# Generated by Django 3.2.7 on 2022-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_remove_productvariant_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
