# Generated by Django 3.2.7 on 2022-09-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_productvariant_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
