# Generated by Django 3.2.7 on 2022-09-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Inverters', 'Inverters'), ('Panels', 'Panels'), ('Rails', 'Rails'), ('Fittings', 'Fittings'), ('Batteries', 'Batteries'), ('Clips', 'Clips'), ('Other', 'Other')], max_length=50),
        ),
    ]
