# Generated by Django 3.2.7 on 2022-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Inverter', 'Inverter'), ('Panel', 'Panel'), ('Rail', 'Rail'), ('Fitting', 'Fitting'), ('Batterie', 'Batterie'), ('Clip', 'Clip'), ('Other', 'Other')], max_length=50),
        ),
    ]
