# Generated by Django 3.2.7 on 2022-09-28 07:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_product_special_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.FileField(default='default.png', upload_to=product.models.image_directory_path),
        ),
    ]
