# Generated by Django 3.2.7 on 2022-12-10 11:31

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(default='default.png', max_length=500, upload_to=product.models.image_directory_path),
        ),
    ]
