# Generated by Django 3.2.7 on 2022-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_productvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cabel_size',
            field=models.CharField(blank=True, help_text='Required for cables', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Inverter', 'Inverter'), ('Panel', 'Panel'), ('Rails & Clips', 'Rails & Clips'), ('Fitting', 'Fitting'), ('Battery', 'Battery'), ('Cables', 'Cables'), ('Other', 'Other')], max_length=50),
        ),
    ]
