# Generated by Django 3.2.7 on 2022-12-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_rename_cabel_size_productvariant_cable_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
