# Generated by Django 3.2.7 on 2022-12-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-id'], 'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
    ]
