# Generated by Django 3.2.7 on 2022-12-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='suitable_roof_style',
            field=models.CharField(blank=True, choices=[('Flat Roof', 'Flat Roof'), ('Pantile Roof', 'Pantile Roof'), ('Plain Roof', 'Plain Roof'), ('Flat tile or slate', 'Flat tile or slate'), ('Meta Roof', 'Metal Roof'), ('New build', 'New build')], help_text='For Hooks/Fittings', max_length=20, null=True),
        ),
    ]
