# Generated by Django 3.2.7 on 2022-12-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_alter_productvariant_suitable_roof_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Inverter', 'Inverter'), ('Panel', 'Panel'), ('Rails', 'Rails & Clips'), ('Fitting', 'Fitting'), ('Battery', 'Battery'), ('Cables', 'Cables'), ('Hook', 'Hook'), ('Other', 'Other')], max_length=50),
        ),
    ]
