# Generated by Django 3.2.7 on 2022-12-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_length_variants',
            field=models.BooleanField(default=False),
        ),
    ]
