# Generated by Django 3.2.7 on 2022-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_product_has_length_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Inverter', 'Inverter'), ('Panel', 'Panel'), ('Rails & Clips', 'Rails & Clips'), ('Fitting', 'Fitting'), ('Battery', 'Battery'), ('Hook', 'Hook'), ('Other', 'Other')], max_length=50),
        ),
    ]
