# Generated by Django 3.2.7 on 2022-08-17 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('postcode', models.IntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('property_type', models.CharField(max_length=50)),
                ('no_floors', models.IntegerField()),
                ('no_bedrooms', models.IntegerField()),
                ('other', models.TextField(blank=True, null=True)),
                ('bill_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('agreement', models.BooleanField(default=False)),
                ('installation_type', models.CharField(max_length=150)),
                ('standalone_installation', models.CharField(blank=True, max_length=70, null=True)),
                ('single_phase', models.BooleanField(default=False)),
                ('spare_way', models.BooleanField(default=False)),
                ('roof_style', models.CharField(blank=True, max_length=20, null=True)),
                ('b_no_panels', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('panels_count', models.IntegerField(blank=True, null=True)),
                ('fitting', models.CharField(blank=True, max_length=50, null=True)),
                ('mount_style_no', models.CharField(blank=True, max_length=200, null=True)),
                ('rails_count', models.FloatField(blank=True, null=True)),
                ('cable_length', models.FloatField(blank=True, null=True)),
                ('storage_system_size', models.CharField(blank=True, max_length=5, null=True)),
                ('storage_cost_option', models.CharField(blank=True, max_length=5, null=True)),
                ('help_with', models.CharField(blank=True, max_length=50, null=True)),
                ('selected_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['user', 'selected_product', 'id'], name='quoute_buil_user_id_f59512_idx'),
        ),
    ]
