# Generated by Django 3.2.7 on 2022-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='single_phase',
        ),
        migrations.AddField(
            model_name='quote',
            name='rails_length',
            field=models.FloatField(blank=True, choices=[('2.2', '2.2'), ('3.3', '3.3')], null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='installation_type',
            field=models.CharField(choices=[('Roof', 'Roof'), ('Standalone', 'Standalone')], max_length=150),
        ),
        migrations.AlterField(
            model_name='quote',
            name='rails_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
