# Generated by Django 3.2.7 on 2022-08-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0002_auto_20220817_1011'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quote',
            name='quoute_buil_user_id_f59512_idx',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='selected_product',
            new_name='selected_panel',
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['user', 'selected_panel', 'id'], name='quoute_buil_user_id_0f9c7f_idx'),
        ),
    ]
