# Generated by Django 3.2.7 on 2022-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0003_auto_20220817_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
