# Generated by Django 3.2.7 on 2022-08-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220818_1149'),
        ('quoute_builder', '0004_quote_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='inverter',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='product.inverter'),
            preserve_default=False,
        ),
    ]
