# Generated by Django 3.2.7 on 2022-08-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0005_quote_inverter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
