# Generated by Django 3.2.7 on 2022-08-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0006_auto_20220819_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
