# Generated by Django 3.2.7 on 2022-08-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0007_auto_20220819_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='phone',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
