# Generated by Django 3.2.7 on 2022-08-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0008_quote_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
    ]
