# Generated by Django 3.2.7 on 2022-08-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0011_auto_20220823_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='inverter',
            field=models.CharField(max_length=250),
        ),
    ]
