# Generated by Django 3.2.7 on 2022-09-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20220917_1254'),
        ('quoute_builder', '0013_auto_20220909_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='help_with',
            new_name='extra_requirement',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='height',
            new_name='roof_height',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='width',
            new_name='roof_width',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='b_no_panels',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='installation_type',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='mount_style_no',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='other',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='rails_length',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='spare_way',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='standalone_installation',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='storage_cost_option',
        ),
        migrations.AddField(
            model_name='quote',
            name='selected_rail',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_rail', to='product.product'),
            preserve_default=False,
        ),
    ]
