# Generated by Django 3.2.7 on 2022-09-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20220917_1254'),
        ('quoute_builder', '0014_auto_20220918_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=250)),
                ('service_price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='cable_length',
            new_name='cable_length_bat_inv',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='extra_requirement',
            new_name='extra_service',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='rails_count',
        ),
        migrations.AlterField(
            model_name='quote',
            name='inverter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_inverter', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='selected_panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='selected_rail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_rail', to='product.productvariant'),
        ),
    ]
