# Generated by Django 3.2.7 on 2022-09-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0015_auto_20220918_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_size', models.CharField(max_length=250)),
                ('storage_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='storage_system_size',
        ),
        migrations.AlterField(
            model_name='quote',
            name='extra_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quoute_builder.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quote',
            name='storage_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quoute_builder.storagesystem'),
        ),
    ]
