# Generated by Django 3.2.7 on 2022-09-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0016_auto_20220918_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='selected_rail',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='total_cost',
        ),
    ]
