# Generated by Django 3.2.7 on 2022-09-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0017_auto_20220918_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.CharField(max_length=10),
        ),
    ]
