# Generated by Django 3.2.7 on 2022-09-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0019_alter_service_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.CharField(help_text='Please make sure to add £ GBP', max_length=50),
        ),
    ]
