# Generated by Django 3.2.7 on 2022-09-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0021_auto_20220918_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='postcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
