# Generated by Django 3.2.7 on 2022-09-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0022_alter_quote_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='storage_cable',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
