# Generated by Django 3.2.7 on 2022-09-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0023_quote_storage_cable'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rail_length',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
