# Generated by Django 3.2.7 on 2022-09-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0024_quote_rail_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='rail_length',
        ),
    ]
