# Generated by Django 3.2.7 on 2022-09-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0026_quote_rail_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
