# Generated by Django 3.2.7 on 2022-09-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0027_quote_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='total_cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
