# Generated by Django 3.2.7 on 2022-09-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0028_alter_quote_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
