# Generated by Django 3.2.7 on 2022-09-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0029_alter_quote_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='bill_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='rail_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
