# Generated by Django 3.2.7 on 2022-09-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0030_auto_20220919_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='cable_length_panel_cons',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
