# Generated by Django 3.2.7 on 2022-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0031_quote_cable_length_panel_cons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='quote',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax',
            field=models.FloatField(default=20),
        ),
    ]
