# Generated by Django 3.2.7 on 2022-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0032_auto_20220919_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='cable_length_panel_cons',
            field=models.FloatField(blank=True, null=True, verbose_name='Cable length from panels to the consumer unit via the Inverter'),
        ),
    ]
