# Generated by Django 3.2.7 on 2022-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0033_alter_quote_cable_length_panel_cons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='cable_length_bat_inv',
            field=models.FloatField(blank=True, null=True, verbose_name='Cable Length from battery location to the inverter'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cable_length_panel_cons',
            field=models.FloatField(blank=True, null=True, verbose_name='Cable Length from panels to the consumer unit via the Inverter'),
        ),
    ]
