# Generated by Django 3.2.7 on 2022-09-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0036_alter_quote_fitting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='fitting',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
