# Generated by Django 3.2.7 on 2022-09-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0038_alter_quote_fitting'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='equipment_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
