# Generated by Django 3.2.7 on 2022-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0039_quote_equipment_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='no_bedrooms',
            field=models.IntegerField(verbose_name='Number of bedrooms'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='no_floors',
            field=models.IntegerField(verbose_name='Number of floors'),
        ),
    ]
