# Generated by Django 3.2.7 on 2022-09-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20220925_1220'),
        ('quoute_builder', '0041_auto_20220925_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='fitting',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_fitting', to='product.productvariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='inverter',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_inverter', to='product.productvariant'),
            preserve_default=False,
        ),
    ]
