# Generated by Django 3.2.7 on 2022-09-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0043_auto_20220925_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='inverter',
        ),
    ]
