# Generated by Django 3.2.7 on 2022-09-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0047_auto_20220927_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rail_type',
            field=models.CharField(blank=True, choices=[('3.3m', '3.3m'), ('3.3m', '3.3m')], max_length=5, null=True),
        ),
    ]
