# Generated by Django 3.2.7 on 2022-09-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0048_quote_rail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='rail_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
