# Generated by Django 3.2.7 on 2022-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoute_builder', '0050_quote_panel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='fitting_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quote',
            name='inverter_price',
            field=models.FloatField(default=0.0),
        ),
    ]
