# Generated by Django 3.2.7 on 2022-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_uuidextensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
    ]
