# Generated by Django 3.2.7 on 2022-08-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_availablecountries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablecountries',
            options={'verbose_name': 'Available Country', 'verbose_name_plural': 'Available Countries'},
        ),
    ]
