# Generated by Django 3.2.7 on 2022-08-18 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_inverter_slug'),
        ('quoute_builder', '0005_quote_inverter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=5)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('products', models.ManyToManyField(blank=True, related_name='panels', to='product.Product')),
                ('quotes', models.ManyToManyField(blank=True, related_name='items', to='quoute_builder.Quote')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
