# Generated by Django 3.2.7 on 2022-08-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20220818_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_product_slug',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
    ]
