# Generated by Django 3.2.7 on 2022-08-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_selected_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='model_type',
        ),
    ]
