# Generated by Django 3.2.7 on 2022-08-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_product_cartitem_model_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='selected_product_slug',
            new_name='product_id',
        ),
    ]
