# Generated by Django 3.2.7 on 2022-08-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_selected_product_slug_cartitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
