# Generated by Django 3.2.7 on 2022-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20220821_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['model_type', 'object_id'], name='cart_cartit_model_t_8e0965_idx'),
        ),
    ]
