# Generated by Django 3.2.7 on 2022-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20220821_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=5, default=True, max_digits=6),
            preserve_default=False,
        ),
    ]
