# Generated by Django 3.2.7 on 2022-08-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cartitem_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
