# Generated by Django 3.2.7 on 2022-08-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20220823_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
