# Generated by Django 3.2.7 on 2022-08-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20220823_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='grand_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
