# Generated by Django 3.2.7 on 2022-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20220901_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
