# Generated by Django 3.2.7 on 2022-09-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_cartitem_variant_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_model_t_8e0965_idx',
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['model_type', 'object_id', 'cart'], name='cart_cartit_model_t_08fb0e_idx'),
        ),
    ]
