# Generated by Django 3.2.7 on 2022-09-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20220903_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
    ]
