# Generated by Django 3.2.7 on 2022-09-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_remove_cart_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
