# Generated by Django 3.2.7 on 2022-09-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_cartitem_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
    ]
