# Generated by Django 3.2.7 on 2022-10-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_auto_20221006_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
