# Generated by Django 4.1 on 2022-08-13 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('postcode', models.PositiveIntegerField()),
                ('house_type', models.CharField(max_length=50)),
                ('no_floors', models.PositiveSmallIntegerField()),
                ('no_bedrooms', models.PositiveSmallIntegerField()),
                ('bill_rate', models.PositiveIntegerField()),
                ('agreement', models.BooleanField(default=False)),
                ('other', djrichtextfield.models.RichTextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='BussinessCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('company_name', models.CharField(max_length=250, unique=True)),
                ('address', models.TextField()),
                ('postcode', models.PositiveIntegerField()),
                ('house_type', models.CharField(max_length=50)),
                ('no_floors', models.PositiveSmallIntegerField()),
                ('no_bedrooms', models.PositiveSmallIntegerField()),
                ('bill_rate', models.PositiveIntegerField()),
                ('agreement', models.BooleanField(default=False)),
                ('other', djrichtextfield.models.RichTextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bussiness', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BussinessCustomer',
                'verbose_name_plural': 'BussinessCustomers',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', 'slug'], name='user_custom_user_id_dbfe4c_idx'),
        ),
        migrations.AddIndex(
            model_name='bussinesscustomer',
            index=models.Index(fields=['user', 'slug'], name='user_bussin_user_id_0a1ea5_idx'),
        ),
    ]
