# Generated by Django 4.1 on 2022-08-13 09:01

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_bussinesscustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='other',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
