# Generated by Django 4.1 on 2022-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_first_name_customer_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Bussiness', 'Bussiness')], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
