# Generated by Django 4.1 on 2022-08-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customer_account_type_customer_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
    ]
