# Generated by Django 3.2.7 on 2022-08-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customer_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='house_type',
            new_name='property_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='provider',
            field=models.CharField(choices=[('Google', 'Google'), ('Email', 'Email')], default=True, max_length=10),
            preserve_default=False,
        ),
    ]
