# Generated by Django 3.2.7 on 2022-08-15 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_auto_20220815_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('Individual', 'Individual'), ('Bussiness', 'Bussiness')], max_length=10)),
                ('slug', models.SlugField()),
                ('address', models.TextField()),
                ('postcode', models.PositiveIntegerField()),
                ('property_type', models.CharField(max_length=50)),
                ('no_floors', models.PositiveSmallIntegerField()),
                ('bill_rate', models.PositiveIntegerField()),
                ('agreement', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('other', djrichtextfield.models.RichTextField(blank=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('provider', models.CharField(choices=[('Google', 'Google'), ('Email', 'Email')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bussiness', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.AddIndex(
            model_name='bussiness',
            index=models.Index(fields=['user', 'slug'], name='user_bussin_user_id_61b7ce_idx'),
        ),
    ]
