# Generated by Django 3.2.7 on 2022-08-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220815_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bussiness',
            options={'verbose_name': 'Bussiness', 'verbose_name_plural': 'Bussinesses'},
        ),
    ]
