# Generated by Django 3.2.7 on 2022-08-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_bussiness_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account_type',
        ),
    ]
