# Generated by Django 3.2.7 on 2022-08-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_auto_20220815_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('address', models.TextField(blank=True, null=True)),
                ('postcode', models.PositiveIntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('no_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bill_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('agreement', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('other', djrichtextfield.models.RichTextField(blank=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('provider', models.CharField(choices=[('Google', 'Google'), ('Email', 'Email')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.DeleteModel(
            name='Bussiness',
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['user', 'slug'], name='user_busine_user_id_769084_idx'),
        ),
    ]
