# Generated by Django 3.2.7 on 2022-09-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220821_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='address',
        ),
        migrations.RemoveField(
            model_name='business',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='business',
            name='bill_rate',
        ),
        migrations.RemoveField(
            model_name='business',
            name='no_floors',
        ),
        migrations.RemoveField(
            model_name='business',
            name='other',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='business',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bill_rate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='no_bedrooms',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='no_floors',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='other',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='property_type',
        ),
    ]
