# Generated by Django 3.2.7 on 2022-09-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20220923_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_category',
        ),
    ]
