# Generated by Django 3.2.7 on 2022-09-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_orderitem_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_cover',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
