# Generated by Django 3.2.7 on 2022-09-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderitem_product_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_cover',
        ),
    ]
