# Generated by Django 3.2.7 on 2022-09-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
