# Generated by Django 3.2.7 on 2022-09-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_product_id',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
