# Generated by Django 3.2.7 on 2022-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_orderitem_order_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_product_id',
            field=models.CharField(max_length=500, verbose_name='Product ID'),
        ),
    ]
